### ISSUE TITLE
[I`d like to c if i can use this in some form

### ISSUE THREAD

**Issue by NicTanghe** [nerfies/nerfies.github.io#1]
This is the only communications channel i could find.

I'm a Vfx student and i'd like to have a look at how this works.
And try running this. I`m somewhat of a noob at ml but i look forward at better understanding it to integrate it into 3d workflows. 

I noticed the source code button on the site is not working, are you guys planning to share it ?

**Comment by keunhong** [comment]
Hi, we plan to release the source code within the next week. It's currently going through the official channels :) Thanks for your interest!

**Comment by Kjue** [comment]
Any progress releasing the code to the wild? Thanks and awesome results so far!

**Comment by keunhong** [comment]
We've just released the code here: https://github.com/google/nerfies

Thanks!
